language: java
jdk: openjdk11
#sudo: required # enabled 30/aug/18 due to travis issue #6593 causing failure

before_install:
  # MATSim config
  #- cd $HOME && git clone --depth=1 --branch=kaibranch https://github.com/matsim-org/matsim.git
  #- cd $HOME/matsim && git checkout kaibranch && git log -1
  #- cd $HOME/matsim/examples && mvn clean install -DskipTests -Dmaven.test.skip -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true
  #- cd $HOME/matsim/matsim && mvn clean install -DskipTests -Dmaven.test.skip -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true
  #
  # Jill config
  #
  - cd $HOME && git clone --depth=1 --branch=dev https://github.com/agentsoz/jill.git
  - cd $HOME/jill && git checkout dev && git log -1
  #- cd $HOME/jill && git reset --hard 2510bed0037cc44520f2627ef85a4fee369e74a9 # fix commit to use
  - cd $HOME/jill && mvn clean install -N
  - cd $HOME/jill/jill && mvn clean install -DskipTests
  #
  # Diffusion Model config
  #
  - cd $HOME && git clone --depth=1 --branch=master https://github.com/agentsoz/diffusion-model.git
  - cd $HOME/diffusion-model && git log -1
  - cd $HOME/diffusion-model && mvn clean install -DskipTests
  #
  # BDI-ABM Integration config
  #
  - cd $HOME && git clone --depth=1 --branch=master https://github.com/agentsoz/bdi-abm-integration.git
  - cd $HOME/bdi-abm-integration && git log -1
  - cd $HOME/bdi-abm-integration && mvn clean install -N
  - cd $HOME/bdi-abm-integration/util && mvn clean install -DskipTests
  - cd $HOME/bdi-abm-integration/integrations/bdi-abm && mvn clean install -DskipTests
  - cd $HOME/bdi-abm-integration/integrations/abm-jill && mvn clean install -DskipTests
  - cd $HOME/bdi-abm-integration/integrations/bdi-matsim && mvn clean install -DskipTests

script:
  - cd $TRAVIS_BUILD_DIR && mvn package -B -Dmatsim.preferLocalDtds=true
# --fail-at-end # stop at first error --> easier to debug
# -Dmaven.test.redirectTestOutputToFile # otherwise nearly impossible to debug
deploy:
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "eesbuildoutputs"
    skip_cleanup: true
    region: ap-southeast-2
    on:
      branch: travis-aws-pipeline-test
  - provider: codedeploy
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "eesbuildoutputs"
    key: target/ees-2.1.1-SNAPSHOT-release.zip
    application: ees-engine-3
    deployment_group: ees-engine-dg-1
    region: ap-southeast-2
    on:
      branch: travis-aws-pipeline-test
env:
  global:
    - MAVEN_OPTS="-Xmx4g -Xms4g"
cache:
  directories:
  - $HOME/.m2
